In [2]:
x = [1,2,3,4]
y = [1,2,3,4]
sum = []

In [4]:
for x,y in zip(x,y):
    sum.append(x+y)

In [5]:
sum

[2, 4, 6, 8]

In [2]:
import numpy as np

In [6]:
np.random.seed(666)
x = 2 * np.random.random(size=100)
y = x * 3. + 4. + np.random.normal(size=100)

In [7]:
x

array([1.40087424, 1.68837329, 1.35302867, 1.45571611, 1.90291591,
       0.02540639, 0.8271754 , 0.09762559, 0.19985712, 1.01613261,
       0.40049508, 1.48830834, 0.38578401, 1.4016895 , 0.58645621,
       1.54895891, 0.01021768, 0.22571531, 0.22190734, 0.49533646,
       0.0464726 , 1.45464231, 0.68006988, 0.39500631, 1.81835919,
       1.95669397, 1.06560509, 0.5182637 , 1.16762524, 0.65138131,
       1.77779863, 1.25280905, 1.63774738, 1.09469084, 0.83342401,
       1.48609438, 0.73919276, 0.15033309, 1.55038596, 0.43881849,
       0.15868425, 0.97356104, 0.3073478 , 1.65693027, 0.38273714,
       0.54081791, 1.12206884, 1.80476078, 1.70357668, 0.83616392,
       0.78695254, 0.03244103, 0.59842674, 0.70755644, 1.78700533,
       1.57227314, 1.54277385, 0.84010971, 1.55205028, 0.92861629,
       0.36354033, 1.76805121, 1.43758454, 1.3437626 , 0.51312727,
       0.86160364, 0.03290715, 0.46998765, 1.02234262, 0.58401848,
       1.00378702, 0.99654626, 0.20754305, 0.89288623, 1.93837

In [8]:
y

array([ 8.91412688,  8.89446981,  8.85921604,  9.04490343,  8.75831915,
        4.01914255,  6.84103696,  4.81582242,  3.68561238,  6.46344854,
        4.61756153,  8.45774339,  3.21438541,  7.98486624,  4.18885101,
        8.46060979,  4.29706975,  4.06803046,  3.58490782,  7.0558176 ,
        4.04787249,  7.46699513,  7.17356576,  6.90706602, 10.06445574,
       10.46043335,  6.56186893,  7.41768066,  6.63306338,  5.16962652,
        8.92568927,  8.81142811,  8.27497363,  9.55931293,  8.31763691,
        8.39594229,  6.46897919,  4.53407649,  9.01364797,  5.23131871,
        5.35968048,  4.92858955,  4.86197655,  8.18778792,  3.53458796,
        3.82545342,  7.06040408, 10.08420404, 10.5135845 ,  5.57993775,
        6.63546582,  2.56719372,  6.94786703,  5.21927087,  9.54664436,
        8.92205488,  9.1083202 ,  7.66433039,  8.04596666,  7.0692907 ,
        6.52268065,  8.89229807, 11.53002966,  6.91636019,  4.88098465,
        6.9583948 ,  2.97055168,  5.2614817 ,  5.8844378 ,  5.04

In [10]:
zero = np.zeros(2)

In [14]:
zero

array([0., 0.])

In [17]:
x.shape

(100,)

In [18]:
y.shape

(100,)

In [21]:
xb = np.hstack([np.ones((len(x),1)),x.reshape(-1,1)])

In [23]:
xb.shape

(100, 2)

In [33]:
theta = np.zeros(xb.shape[1])

In [34]:
theta.shape

(2,)

In [28]:
_y = xb.dot(theta)

In [30]:
_y.shape

(100,)

In [37]:
_=(_y-y).dot(xb[:,1])

In [38]:
_

-797.683929083539

In [4]:
n = 10
m = 10
np.random.normal(size=(m,n))

array([[ 0.89949874,  0.2095079 ,  0.19614208, -1.02219381, -0.04587743,
        -0.03923919, -1.18555138,  2.26675891,  0.22018385,  0.41204793],
       [ 1.05997967, -0.51872748, -0.16493593, -0.37396014,  0.11775971,
        -0.86815014,  1.40741631,  0.81043262,  0.0347856 ,  0.49424229],
       [-1.00306701,  0.0209649 , -1.05201056,  1.10080357, -0.45352959,
        -0.63377648, -0.29254933, -1.81538881,  0.21495324,  1.54284126],
       [-0.64687528, -1.34600622,  1.47612463,  0.31662004, -0.75420516,
         0.32142156,  1.33109102, -0.068138  , -0.38601144,  2.21363792],
       [ 0.37790937,  0.45552727,  0.59969463, -1.87378288,  0.17462133,
         0.35906094,  1.35860261, -0.89422143, -2.18709164,  0.12871525],
       [-1.82076185,  0.80629927, -0.12181339, -0.09968967,  1.36584605,
         0.00597479,  1.08999711, -0.70243213, -0.26821217, -1.33410316],
       [-1.30000423,  1.06031449, -1.58191586,  0.19026865, -0.27046322,
        -0.32207119, -0.86510227, -2.27054051

In [7]:
np.random.uniform(0.0, 100.0, size=n+1)

array([46.08594927, 29.17400954, 92.47941674, 28.01300552,  6.23431888,
       14.54783034, 10.20236375,  4.38478308, 42.96416957, 77.29210356,
       38.06589674])