In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

### train_test_split

In [6]:
shuffle_indexes = np.random.permutation(len(X))

In [7]:
shuffle_indexes

array([ 36,  85,  58,  39,  31,  15, 124, 114, 147,  79,  78,  49,  63,
       134, 146,  12,  47, 143,  14, 139, 121, 123,   4, 122,  21,  40,
       116, 120,  34,  59,  48, 118,  53,  56,  66,  50, 142, 103,   1,
       130,  76, 148, 110,  35,  94,  22,  30,  29, 106,   3, 129,  71,
       113, 104,   2,  33, 105,  24, 108, 149, 119,  83,  84, 144,  65,
        87, 107, 125,  17, 112,  96, 102,  69, 100, 115,  45,  57,  38,
        91, 135,  70,  98,  60, 140,  61, 138,  72,  73,  27,   9,  75,
       133,  51,  89, 126,  95, 136,  28, 117,  43,  13,  44,  18,   5,
         7,  55,   8,   6, 137,  68,  26,  74,  19,  46, 128,  10,  16,
       132,  54,  32,  62,  23, 127,  81,  77,  67, 141,  64,  11,  99,
       109,  42,  88,  92,  90, 101,   0, 111,  80,  25,  41,  86,  52,
        93,  20, 131,  97, 145,  82,  37])

In [8]:
test_ratio = 0.2

In [9]:
test_size = int(len(X)*test_ratio)

In [10]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [13]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

### 使用我们的算法

In [14]:
from playML.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [17]:
from playML.kNN import KNNClassifier

In [18]:
my_knn_clf = KNNClassifier(k=3)

In [19]:
my_knn_clf.fit(X_train, y_train)

In [20]:
y_predict = my_knn_clf.predict(X_test)

In [21]:
y_predict

array([2, 1, 2, 1, 1, 0, 1, 1, 0, 0, 2, 2, 1, 0, 2, 2, 1, 0, 0, 2, 0, 0,
       2, 1, 2, 2, 2, 1, 2, 2])

In [22]:
y_test

array([2, 1, 2, 1, 1, 0, 1, 1, 0, 0, 2, 2, 1, 0, 2, 2, 1, 0, 0, 2, 0, 0,
       2, 1, 2, 2, 2, 1, 2, 2])

In [23]:
sum(y_predict == y_test)

30